### ISSUE TITLE
it not working.

### ISSUE THREAD

**Issue by mhtranbn** [ezefranca/EFInternetIndicator#1]
it not working. many thank for supports @ezefranca

**Comment by mhtranbn** [comment]
Many thank!

**Comment by ezefranca** [comment]
@mhtranbn Hey, how are you? Whats your problem with the code?

**Comment by mhtranbn** [comment]
sorry, first i try it with simunator it fail, but now i test it on device it works. thanks

**Comment by ezefranca** [comment]
@mhtranbn Oh, thank you for this. I Will added in README a warning about that :)
