### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by rmvz3** [ezefranca/EFInternetIndicator#2]
Please

**Comment by ezefranca** [comment]
@rmvz3  Thanks for your message. For now, use 

` pod 'EFInternetIndicator', :git => 'https://github.com/ezefranca/EFInternetIndicator.git'`

In the weekend I will trunk this version.

**Comment by rmvz3** [comment]
Thank you for updating. It seems SwiftMessages have updated too and they don't match each other anymore tho.

**Comment by ezefranca** [comment]
Fixed.
